# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Testnet & Development Bridge Tasks - Build and deploy Function App

on:
  push:
    branches:
      - develop
    paths:
      - 'serverless/bridge-tasks/**'
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME_TESTNET: sienna-bridge-tasks-testnet
  AZURE_FUNCTIONAPP_NAME_DEV: sienna-bridge-tasks-dev
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'serverless/bridge-tasks' # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '16.x' # set this to the node version to use (supports 8.x, 10.x, 12.x)

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:

    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v2

    - name: Setup Node ${{ env.NODE_VERSION }} Environment
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: 'Resolve Project Dependencies Using Npm'
      shell: pwsh
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        npm i -g pnpm@7.5.0
        pnpm install
        pnpm run build:production
        pnpm run test --if-present
        popd

    - name: 'Run Azure Functions Action Testnet'
      uses: Azure/functions-action@v1
      id: bridge-tasks-testnet
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME_TESTNET }}
        slot-name: 'production'
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        publish-profile: ${{ secrets.CF_SIENNA_BRIDGE_TASKS_TESTNET }}

    - name: 'Run Azure Functions Action Dev'
      uses: Azure/functions-action@v1
      id: bridge-tasks-dev
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME_DEV }}
        slot-name: 'production'
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        publish-profile: ${{ secrets.CF_SIENNA_BRIDGE_TASKS_DEV }}
