name: Azure App Service - EthereumBridgeBackend TestNet & Dev, Build and deploy NodeJS app

on:
  push:
    branches:
      - develop
    paths-ignore:
      - 'serverless/**'
      - '.github/**'

permissions:
      id-token: write
      contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: testnet
    steps:
    # checkout the repo
    - name: 'Checkout GitHub Action' 
      uses: actions/checkout@main
   
    - uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'
    
    - name: 'npm install, build, and test'
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present

    - name: ETHEREUMBRIDGEBACKEND_TESTNET    
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'EthereumBridgeBackendTestnet'
        package: .

    - name: ETHEREUMBRIDGEBACKEND_DEV    
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'EthereumBridgeBackendDevelopment'
        package: .

    # Azure logout 
    - name: logout
      run: |
        az logout